package com.xwrokz.tostring.stringRunner;

import com.xwrokz.tostring.external.*;



public class equalsRunner {
    public static void main(String[] args) {
        System.out.println("============================1===================================");
        AirConditioner airConditioner1=new AirConditioner("Dell",6,"Black","100Rs");
        AirConditioner airConditioner2=new AirConditioner("Dell",6,"Black","400Rs");
        System.out.println("Both are same: "+airConditioner1.equals(airConditioner2));
        System.out.println("============================2===================================");
        Animal animal1=new Animal("Lion","America","brown");
        Animal animal2=new Animal("Peacock","India","Purple");
        System.out.println("Both are same: "+animal1.equals(animal2));
        System.out.println("============================3===================================");
        Bag bag1=new Bag("Nike",2000,"black");
        Bag bag2=new Bag("Puma",4000,"white");
        System.out.println("Both are same: "+bag1.equals(bag2));
        System.out.println("============================4===================================");
        Bat bat1=new Bat("India",20,true);
        Bat bat2=new Bat("India",40,true);
        System.out.println("Both are same: "+bat1.equals(bat2));
        System.out.println("============================5===================================");
        Bear bear1=new Bear("America",200,"Fish");
        Bear bear2=new Bear("india",250,"Fish");
        System.out.println("Both are same: "+bear1.equals(bear2));
        System.out.println("============================6===================================");
        Bed bed1=new Bed("Iron",32,"Brown");
        Bed bed2=new Bed("Wood",25,"Black");
        System.out.println("Both are same: "+bed1.equals(bed2));
        System.out.println("============================7===================================");
        Bicycle bicycle1=new Bicycle("MI",32,"Plastic");
        Bicycle bicycle2=new Bicycle("Fier Fox",25,"Carbon Fiber");
        System.out.println("Both are same: "+bicycle1.equals(bicycle2));
        System.out.println("============================8===================================");
        Bike bike1=new Bike("GT350",6,"Carbon Fiber");
        Bike bike2=new Bike("Java",5,"Carbon Fiber");
        System.out.println("Both are same: "+bike1.equals(bike2));
        System.out.println("============================9===================================");
        Blender blender1=new Blender("Lenevo",1000,"Yellow");
        Blender blender2=new Blender("Hier",1000,"Red");
        System.out.println("Both are same: "+blender1.equals(blender2));
        System.out.println("============================10===================================");
        Book book1=new Book("Diary","vaibhav",100);
        Book book2=new Book("Diary","chaitanya",200);
        System.out.println("Both are same: "+book1.equals(book2));
        System.out.println("============================10===================================");
        Bucket bucket1=new Bucket("Jug",200,'M');
        Bucket bucket2=new Bucket("ROY",600,'L');
        System.out.println("Both are same: "+bucket1.equals(bucket2));
        System.out.println("============================11===================================");
        Camera camera1=new Camera("Canon",248,"Focus");
        Camera camera2=new Camera("Nikon",128,"Raw");
        System.out.println("Both are same: "+camera1.equals(camera2));
        System.out.println("============================12===================================");
        Cap cap1=new Cap("PUMA",200,"Black");
        Cap cap2=new Cap("PUMA",120,"Blue");
        System.out.println("Both are same: "+cap1.equals(cap2));
        System.out.println("============================13===================================");
        Car car1=new Car("2018",20,"Black");
        Car car2=new Car("2015",12,"Blue");
        System.out.println("Both are same: "+car1.equals(car2));
        System.out.println("============================14===================================");
        Cat cat1=new Cat("Persian",20,"Black");
        Cat cat2=new Cat("Persian",12,"White");
        System.out.println("Both are same: "+cat1.equals(cat2));
        System.out.println("============================15===================================");
        Chair chair1=new Chair("JUMBO",200,"Black");
        Chair chair2=new Chair("ROY",200,"White");
        System.out.println("Both are same: "+chair1.equals(chair2));
        System.out.println("============================16===================================");
        Cloth cloth1=new Cloth("Jeans","Red","Xl");
        Cloth cloth2=new Cloth("Nylon","Grey","L");
        System.out.println("Both are same: "+cloth1.equals(cloth2));
        System.out.println("============================16===================================");
        Coffee coffee1=new Coffee("Latte",200,"Bangalore");
        Coffee coffee2=new Coffee("Capacino",200,"Goa");
        System.out.println("Both are same: "+coffee1.equals(coffee2));
        System.out.println("============================17===================================");
        Color color1=new Color("Rambow",200,"2026");
        Color color2=new Color("Camel",200,"2026");
        System.out.println("Both are same: "+color1.equals(color2));
        System.out.println("============================18===================================");
        Computer computer1=new Computer("Acer",16,"Snapdragon");
        Computer computer2=new Computer("Asus",16,"GeforceRTX");
        System.out.println("Both are same: "+computer1.equals(computer2));
        System.out.println("============================19===================================");
        Cow cow1=new Cow("Normal Cow",true,false);
        Cow cow2=new Cow("Normal Cow",true,true);
        System.out.println("Both are same: "+cow1.equals(cow2));
        System.out.println("============================20===================================");
        Crocodile crocodile1=new Crocodile("America",8,"Fish");
        Crocodile crocodile2=new Crocodile("India",9,"Deer");
        System.out.println("Both are same: "+crocodile1.equals(crocodile2));
        System.out.println("============================21===================================");
        Dog dog1=new Dog("German Sheaperd",18,"Samll");
        Dog dog2=new Dog("Dobber man ",19,"Large");
        System.out.println("Both are same: "+dog1.equals(dog2));
        System.out.println("============================22===================================");
        Dolphine dolphine1=new Dolphine("Water",180,true);
        Dolphine dolphine2=new Dolphine("Water",190,true);
        System.out.println("Both are same: "+dolphine1.equals(dolphine2));
        System.out.println("============================21===================================");
        Door door1=new Door("Black",1800,'X');
        Door door2=new Door("White",1900,'M');
        System.out.println("Both are same: "+door1.equals(door2));
        System.out.println("============================22===================================");
        Duck duck1=new Duck("Black","water",true);
        Duck duck2=new Duck("White","water",true);
        System.out.println("Both are same: "+duck1.equals(duck2));
        System.out.println("============================23===================================");
        Eagle eagle1=new Eagle("Forest",29,"Fish");
        Eagle eagle2=new Eagle("Forest",30,"Rat");
        System.out.println("Both are same: "+eagle1.equals(eagle2));
        System.out.println("============================24===================================");
        EarBuds earBuds1=new EarBuds("Boat",2900,"Black");
        EarBuds earBuds2=new EarBuds("One Plus",3000,"White");
        System.out.println("Both are same: "+earBuds1.equals(earBuds2));
        System.out.println("============================25===================================");
        EarRings earRings1=new EarRings("gold",3000,"Glod");
        EarRings earRings2=new EarRings("Platinum",3000,"White");
        System.out.println("Both are same: "+earRings1.equals(earRings2));
        System.out.println("============================26===================================");
        Fan fan1=new Fan("Chroma",3000,"Brown");
        Fan fan2=new Fan("Bajaj",3000,"White");
        System.out.println("Both are same: "+fan1.equals(fan2));
        System.out.println("============================27===================================");
        Food food1=new Food("Mango",300,"Bangalore");
        Food food2=new Food("Mango",300,"Goa");
        System.out.println("Both are same: "+food1.equals(food2));
        System.out.println("============================28===================================");
        Fruit fruit1=new Fruit("Mango",3,400);
        Fruit fruit2=new Fruit("Mango",3,400);
        System.out.println("Both are same: "+fruit1.equals(fruit2));
        System.out.println("============================29===================================");
        Games games1=new Games("BGIM","Mangalore","4 O'Clock ");
        Games games2=new Games("BGIM","Bangalore","6 O'Clock ");
        System.out.println("Both are same: "+games1.equals(games2));
        System.out.println("============================30===================================");
        Guitar guitar1=new Guitar("Rock",3,"Electric");
        Guitar guitar2=new Guitar("MI",9,"Electric");
        System.out.println("Both are same: "+guitar1.equals(guitar2));
        System.out.println("============================31===================================");
        HairDryer hairDryer1=new HairDryer("Mi",3,"Brown");
        HairDryer hairDryer2=new HairDryer("MI",9,"White");
        System.out.println("Both are same: "+hairDryer1.equals(hairDryer2));
        System.out.println("============================32===================================");
        Helmet helmet1=new Helmet("Mi","Carbon Fiber",4);
        Helmet helmet2=new Helmet("MI","Carbon Fiber",5);
        System.out.println("Both are same: "+helmet1.equals(helmet2));
        System.out.println("============================33===================================");
        Home home1=new Home("3BHK",4000,"Goa");
        Home home2=new Home("3BHK",9000,"Bangalore");
        System.out.println("Both are same: "+home1.equals(home2));
        System.out.println("============================34===================================");
        Horse horse1=new Horse("Unicon","Black",8);
        Horse horse2=new Horse("Horse","Black",8);
        System.out.println("Both are same: "+horse1.equals(horse2));
        System.out.println("============================35===================================");
        Human human1=new Human("Vaibhav",23,"Male");
        Human human2=new Human("Chaitanya",23,"Female");
        System.out.println("Both are same: "+human1.equals(human2));
        System.out.println("============================36===================================");
        IceCream iceCream1=new IceCream("Butter Scotch",230,"Rajajinagar");
        IceCream iceCream2=new IceCream("Vanila",230,"Vijayanagr");
        System.out.println("Both are same: "+iceCream1.equals(iceCream2));
        System.out.println("============================37===================================");
        Jug jug1=new Jug("Red",3,"Plastic");
        Jug jug2=new Jug("Grey",2,"Plastic");
        System.out.println("Both are same: "+jug1.equals(jug2));
        System.out.println("============================38===================================");
        Kangaroo kangaroo1=new Kangaroo("Forest",309,8);
        Kangaroo kangaroo2=new Kangaroo("Forest",309,8);
        System.out.println("Both are same: "+kangaroo1.equals(kangaroo2));
        System.out.println("============================39===================================");
        Koala koala1=new Koala("Forest","Fish",true);
        Koala koala2=new Koala("Forest","Fish",true);
        System.out.println("Both are same: "+koala1.equals(koala2));
        System.out.println("============================40===================================");
        Lamp lamp1=new Lamp("Mi","White",10);
        Lamp lamp2=new Lamp("Mi","White",20);
        System.out.println("Both are same: "+lamp1.equals(lamp2));
        System.out.println("============================41===================================");
        Laptop laptop1=new Laptop("Acer",70000,"Black");
        Laptop laptop2=new Laptop("Acer",70000,"Black");
        System.out.println("Both are same: "+laptop1.equals(laptop2));
        System.out.println("============================42===================================");
        LaptopBag laptopBag1=new LaptopBag("Fabric",3,"Black");
        LaptopBag laptopBag2=new LaptopBag("Fabric",4,"Black");
        System.out.println("Both are same: "+laptopBag1.equals(laptopBag2));
        System.out.println("============================43===================================");
        Lion lion1=new Lion("Forest",3,"Danger");
        Lion lion2=new Lion("Forest",4,"Danger");
        System.out.println("Both are same: "+lion1.equals(lion2));
        System.out.println("============================44===================================");
        Mattress mattress1=new Mattress("Local",3,"Nylon");
        Mattress mattress2=new Mattress("Branded",4,"Polyster");
        System.out.println("Both are same: "+mattress1.equals(mattress2));
        System.out.println("============================45===================================");
        Microwave microwave1=new Microwave("Dell",3,"Black");
        Microwave microwave2=new Microwave("Hier",4,"Marroon");
        System.out.println("Both are same: "+microwave1.equals(microwave2));
        System.out.println("============================46===================================");
        MicrowaveOven microwaveOven1=new MicrowaveOven("Dell",4,"Black");
        MicrowaveOven microwaveOven2=new MicrowaveOven("Hier",6,"Marroon");
        System.out.println("Both are same: "+microwaveOven1.equals(microwaveOven2));
        System.out.println("============================47===================================");
        Mug mug1=new Mug("Plastic","Grey",7);
        Mug mug2=new Mug("Plastic","Grey",7);
        System.out.println("Both are same: "+mug1.equals(mug2));
        System.out.println("============================48===================================");
        Office office1=new Office("X-Workz",8,7);
        Office office2=new Office("Q-Spider",8,7);
        System.out.println("Both are same: "+office1.equals(office2));
        System.out.println("============================49===================================");
        Ostrich ostrich1=new Ostrich("Forest",800,true);
        Ostrich ostrich2=new Ostrich("Forest",800,true);
        System.out.println("Both are same: "+ostrich1.equals(ostrich2));
        System.out.println("============================50===================================");
        Panda panda1=new Panda("Forest","Fish",true);
        Panda panda2=new Panda("Forest","Fish",true);
        System.out.println("Both are same: "+panda1.equals(panda2));
        System.out.println("============================51===================================");
        Pant pant1=new Pant("Jeans",6000,"Blue");
        Pant pant2=new Pant("Jeans",3000,"Blue");
        System.out.println("Both are same: "+pant2.equals(pant2));
        System.out.println("============================52===================================");
        Parakeet parakeet1=new Parakeet("Green","Forest",true);
        Parakeet parakeet2=new Parakeet("Green","Forest",true);
        System.out.println("Both are same: "+parakeet1.equals(parakeet2));
        System.out.println("============================53===================================");
        Parrot parrot1=new Parrot("Green","Forest",true);
        Parrot parrot2=new Parrot("Green","Forest",false);
        System.out.println("Both are same: "+parrot1.equals(parrot2));
        System.out.println("============================54===================================");
        Pen pen1=new Pen("Montex","Blue",2);
        Pen pen2=new Pen("Ronito","Black",1);
        System.out.println("Both are same: "+pen1.equals(pen2));
        System.out.println("============================55===================================");
        Penguin penguin1=new Penguin("Antarctica",60,"Fish");
        Penguin penguin2=new Penguin("Antarctica",50,"Fish");
        System.out.println("Both are same: "+penguin1.equals(penguin2));
        System.out.println("============================56===================================");
        Phone phone1=new Phone("Iphone",60000,"White");
        Phone phone2=new Phone("MI",15000,"White");
        System.out.println("Both are same: "+phone1.equals(phone2));
        System.out.println("============================57===================================");
        Plane plane1=new Plane("Goa",60,"V8");
        Plane plane2=new Plane("Mumbai",150,"V8");
        System.out.println("Both are same: "+plane1.equals(plane2));
        System.out.println("============================58===================================");
        PowerBank powerBank1=new PowerBank("Dell",6000,"Black");
        PowerBank powerBank2=new PowerBank("Syska",1500,"White");
        System.out.println("Both are same: "+powerBank1.equals(powerBank2));
        System.out.println("============================59===================================");
        Printer printer1=new Printer("Dell","Electric",8000);
        Printer printer2=new Printer("Syska","Electric",8000);
        System.out.println("Both are same: "+printer1.equals(printer2));
        System.out.println("============================60===================================");
        Rabbit rabbit1=new Rabbit("local",true,true);
        Rabbit rabbit2=new Rabbit("hybrid",true,true);
        System.out.println("Both are same: "+rabbit1.equals(rabbit2));
        System.out.println("============================61===================================");
        Refrigerator refrigerator1=new Refrigerator("Hier",60,"Grey");
        Refrigerator refrigerator2=new Refrigerator("Samsung",60,"Grey");
        System.out.println("Both are same: "+refrigerator1.equals(refrigerator2));
        System.out.println("============================62===================================");
        School school1=new School("Vaibhav","Maths",10);
        School school2=new School("Sankalp","Science",9);
        System.out.println("Both are same: "+school1.equals(school2));
        System.out.println("============================63===================================");
        Seagull seagull1=new Seagull("Water",9,"Fish");
        Seagull seagull2=new Seagull("Water",9,"Fish");
        System.out.println("Both are same: "+seagull1.equals(seagull2));
        System.out.println("============================64===================================");
        Shark shark1=new Shark("Great white ",true,true);
        Shark shark2=new Shark("Tiger",true,true);
        System.out.println("Both are same: "+shark1.equals(shark2));
        System.out.println("============================65===================================");
        Shirt shirt1=new Shirt(" Nike ",2000,'L');
        Shirt shirt2=new Shirt("Nike",2000,'L');
        System.out.println("Both are same: "+shirt1.equals(shirt2));
        System.out.println("============================66===================================");
        Shoe shoe1=new Shoe(" Nike ",2000,"Black");
        Shoe shoe2=new Shoe("Puma",2000,"Red");
        System.out.println("Both are same: "+shoe1.equals(shoe2));
        System.out.println("============================67===================================");
        SkateBoard skateBoard1=new SkateBoard("Adiddas","Wood",'L');
        SkateBoard skateBoard2=new SkateBoard("Puma","Fiber",'S');
        System.out.println("Both are same: "+skateBoard1.equals(skateBoard2));
        System.out.println("============================68===================================");
        SmartPhone smartPhone1=new SmartPhone("MI",64,true);
        SmartPhone smartPhone2=new SmartPhone("IPhone",32,true);
        System.out.println("Both are same: "+smartPhone1.equals(smartPhone2));
        System.out.println("============================69===================================");
        SmartWatch smartWatch1=new SmartWatch("MI",true,true);
        SmartWatch smartWatch2=new SmartWatch("Mi",true,true);
        System.out.println("Both are same: "+smartWatch1.equals(smartWatch2));
        System.out.println("============================70===================================");
        Snake snake1=new Snake("Cobra",true,true);
        Snake snake2=new Snake("Python",true,true);
        System.out.println("Both are same: "+snake1.equals(snake2));
        System.out.println("============================71===================================");
        Soap soap1=new Soap("Wheel",100,"Jasmine");
        Soap soap2=new Soap("Rin",100,"Rose");
        System.out.println("Both are same: "+soap1.equals(soap2));
        System.out.println("============================72===================================");
        Speaker speaker1=new Speaker("JBL",100,"Orange");
        Speaker speaker2=new Speaker("Boat",100,"Black");
        System.out.println("Both are same: "+speaker1.equals(speaker2));
        System.out.println("Both are same: "+soap1.equals(soap2));
        System.out.println("============================73===================================");
        StandMixer standMixer1=new StandMixer("Hier",100,"Orange");
        StandMixer standMixer2=new StandMixer("LG",100,"Black");
        System.out.println("Both are same: "+standMixer1.equals(standMixer2));
        System.out.println("============================74===================================");
        Suitcase suitcase1=new Suitcase("Sky Bag",10,"Orange");
        Suitcase suitcase2=new Suitcase("American Tuorist",10,"Black");
        System.out.println("Both are same: "+suitcase1.equals(suitcase2));
        System.out.println("============================75===================================");
        SunGlass sunGlass1=new SunGlass("RayBan",1000,"White");
        SunGlass sunGlass2=new SunGlass("Lens", 400,"Black");
        System.out.println("Both are same: "+sunGlass1.equals(sunGlass2));
        System.out.println("============================76===================================");
        Swan swan1=new Swan("White","Water",5);
        Swan swan2=new Swan("White", "Water",5);
        System.out.println("Both are same: "+swan1.equals(swan2));
        System.out.println("============================77===================================");
        Table table1=new Table("Metal",700,"Black");
        Table table2=new Table("Plastic", 800,"Brown");
        System.out.println("Both are same: "+table1.equals(table2));
        System.out.println("============================78===================================");
        TeddyBear teddyBear1=new TeddyBear("White",true,true);
        TeddyBear teddyBear2=new TeddyBear("White", true,true);
        System.out.println("Both are same: "+teddyBear1.equals(teddyBear2));
        System.out.println("============================79===================================");
        Television television1=new Television("Sony",32,"302");
        Television television2=new Television("MI", 26,"368");
        System.out.println("Both are same: "+television1.equals(television2));
        System.out.println("============================80===================================");
        Tent tent1=new Tent("Aristocart",32,"Red");
        Tent tent2=new Tent("Polo", 26,"Green");
        System.out.println("Both are same: "+tent1.equals(tent2));
        System.out.println("============================81===================================");
        Tiger tiger1=new Tiger("Forest",320,"Orange");
        Tiger tiger2=new Tiger("Forest", 340,"White");
        System.out.println("Both are same: "+tiger1.equals(tiger2));
        System.out.println("============================82===================================");
        Toaster toaster1=new Toaster("Hier",320,"Black");
        Toaster toaster2=new Toaster("LG", 340,"White");
        System.out.println("Both are same: "+toaster1.equals(toaster2));
        System.out.println("============================83===================================");
        Tortoise tortoise1=new Tortoise("Water",320,"Fish");
        Tortoise tortoise2=new Tortoise("Land", 340,"Fish");
        System.out.println("Both are same: "+tortoise1.equals(tortoise2));
        System.out.println("============================84===================================");
        Treadmill treadmill1=new Treadmill("Sony",320,"Black");
        Treadmill treadmill2=new Treadmill("FierFox", 340,"Gray");
        System.out.println("Both are same: "+treadmill1.equals(treadmill2));
        System.out.println("============================85===================================");
        Tree tree1=new Tree("Mango",150,"Goa");
        Tree tree2=new Tree("Mango", 150,"Goa");
        System.out.println("Both are same: "+tree1.equals(tree2));
        System.out.println("============================85===================================");
        Trolley trolley1=new Trolley("Sona","Iron","White");
        Trolley trolley2=new Trolley("Dona", "Iron","White");
        System.out.println("Both are same: "+trolley1.equals(trolley2));
        System.out.println("============================86===================================");
        Truck truck1=new Truck("1952",30,"V8");
        Truck truck2=new Truck("1953", 30,"V9");
        System.out.println("Both are same: "+truck1.equals(truck2));
        System.out.println("============================87===================================");
        TubeLight tubeLight1=new TubeLight("Cello",300,"Red");
        TubeLight tubeLight2=new TubeLight("Bajaj", 300,"White");
        System.out.println("Both are same: "+tubeLight1.equals(tubeLight2));
        System.out.println("============================88===================================");
        VaccumeCleaner vaccumeCleaner1=new VaccumeCleaner("Sony",300,"Black");
        VaccumeCleaner vaccumeCleaner2=new VaccumeCleaner("Laaz", 300,"White");
        System.out.println("Both are same: "+vaccumeCleaner1.equals(vaccumeCleaner2));
        System.out.println("============================89===================================");
        WashingMachine washingMachine1=new WashingMachine("Lenevo",3,"Black");
        WashingMachine washingMachine2=new WashingMachine("IFB", 8,"White");
        System.out.println("Both are same: "+washingMachine1.equals(washingMachine2));
        System.out.println("============================90===================================");
        Watch watch1=new Watch("Titan",3000,"Black");
        Watch watch2=new Watch("Titan", 3000,"Black");
        System.out.println("Both are same: "+watch1.equals(watch2));





    }
}
