package com.xwrokz.tostring.stringRunner;

import com.xwrokz.tostring.external.*;

import java.util.IdentityHashMap;

public class StringRunner {
    public static void main(String[] args) {

        Jug jug=new Jug("Black",4,"Plastic");
        System.out.println(jug);
        System.out.println("hashCode Manual: " +jug.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(jug));
        System.out.println("================================================================");
        Bucket bucket=new Bucket("Black",400,'M');
        System.out.println(bucket);
        System.out.println("hashCode Manual: " +bucket.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(bucket));
        System.out.println("================================================================");
        Door door=new Door("Brown",4000,'L');
        System.out.println(door);
        System.out.println("hashCode Manual: " +door.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(door));
        System.out.println("================================================================");
        School school=new School("Vaibhav","English",10);
        System.out.println(school);
        System.out.println("hashCode Manual: " +school.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(school));
        System.out.println("================================================================");
        EarRings earRings=new EarRings("Gold",700,"Gold");
        System.out.println(earRings);
        System.out.println("hashCode Manual: " +earRings.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(earRings));
        System.out.println("================================================================");
        Office office=new Office("X-Workz",8,4);
        System.out.println(office);
        System.out.println("hashCode Manual: " +office.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(office));
        System.out.println("================================================================");
        Games games=new Games("UNO","Bangalore","11:30 AM");
        System.out.println(games);
        System.out.println("hashCode Manual: " +games.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(games));
        System.out.println("================================================================");
        Shirt shirt=new Shirt("Nike",900,'S');
        System.out.println(shirt);
        System.out.println("hashCode Manual: " +shirt.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(shirt));
        System.out.println("================================================================");
        Animal animal=new Animal("Elephant","India","Grey");
        System.out.println(animal);
        System.out.println("hashCode Manual: " +animal.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(animal));
        System.out.println("================================================================");
        EarBuds earBuds=new EarBuds("One Plus",2000,"Black");
        System.out.println(earBuds);
        System.out.println("hashCode Manual: " +earBuds.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(earBuds));
        System.out.println("================================================================");
        Fan fan=new Fan("Bajaz",1000,"Cream");
        System.out.println(fan);
        System.out.println("hashCode Manual: " +fan.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(fan));
        System.out.println("================================================================");
        Watch watch=new Watch("Fastrack",3000,"Black");
        System.out.println(watch);
        System.out.println("hashCode Manual: " +watch.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(watch));
        System.out.println("================================================================");
        SunGlass sunGlass=new SunGlass("HRX",5000,"Black");
        System.out.println(sunGlass);
        System.out.println("hashCode Manual: " +sunGlass.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(sunGlass));
        System.out.println("================================================================");
        Shoe shoe=new Shoe("PUMA",5000,"White");
        System.out.println(shoe);
        System.out.println("hashCode Manual: " +shoe.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(shoe));
        System.out.println("================================================================");
        Window window=new Window("Wooden",8000,"Cream");
        System.out.println(window);
        System.out.println("hashCode Manual: " +window.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(window));
        System.out.println("================================================================");
        Cap cap=new Cap("WoodLand",800,"Dark Blue");
        System.out.println(cap);
        System.out.println("hashCode Manual: " +cap.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(cap));
        System.out.println("================================================================");
        Chair chair=new Chair("Durian",600,"Brown");
        System.out.println(chair);
        System.out.println("hashCode Manual: " +chair.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(chair));
        System.out.println("================================================================");
        Pant pant=new Pant("Jeans",1500,"Blue");
        System.out.println(pant);
        System.out.println("hashCode Manual: " +pant.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(pant));
        System.out.println("================================================================");
        Phone phone=new Phone("Iphone",1.5f,"Blue");
        System.out.println(phone);
        System.out.println("hashCode Manual: " +phone.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(phone));
        System.out.println("================================================================");
        Laptop laptop=new Laptop("Mac-Book",2.5f,"Silver");
        System.out.println(laptop);
        System.out.println("hashCode Manual: " +laptop.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(laptop));
        System.out.println("================================================================");
        PowerBank powerBank=new PowerBank("Syska",2000,"White");
        System.out.println(powerBank);
        System.out.println("hashCode Manual: " +powerBank.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(powerBank));
        System.out.println("================================================================");
        IceCream iceCream=new IceCream("Chocolate",200,"Vijayanagar");
        System.out.println(iceCream);
        System.out.println("hashCode Manual: " +iceCream.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(iceCream));
        System.out.println("================================================================");
        Fruit fruit=new Fruit("Mango",2,500);
        System.out.println(fruit);
        System.out.println("hashCode Manual: " +fruit.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(fruit));
        System.out.println("================================================================");
        TubeLight tubeLight=new TubeLight("Bajaj",200,"White");
        System.out.println(tubeLight);
        System.out.println("hashCode Manual: " +tubeLight.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(tubeLight));
        System.out.println("================================================================");
        Bag bag=new Bag("Sky Bag",2000,"Red");
        System.out.println(bag);
        System.out.println("hashCode Manual: " +bag.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(bag));
        System.out.println("================================================================");
        Tree tree=new Tree("Coconut",20,"Goa");
        System.out.println(tree);
        System.out.println("hashCode Manual: " +tree.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(tree));
        System.out.println("================================================================");
        Home home=new Home("Flat",2000,"Rajajinagar");
        System.out.println(home);
        System.out.println("hashCode Manual: " +home.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(home));
        System.out.println("================================================================");
        Coffee coffee=new Coffee("Latte",500,"BTM Layout");
        System.out.println(coffee);
        System.out.println("hashCode Manual: " +coffee.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(coffee));
        System.out.println("================================================================");
        Food food=new Food("Biriyani",500,"Mangalore");
        System.out.println(food);
        System.out.println("hashCode Manual: " +food.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(food));
        System.out.println("================================================================");
        Color color=new Color("Cameline",500,"01/07/2024");
        System.out.println(color);
        System.out.println("hashCode Manual: " +color.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(color));
        System.out.println("================================================================");
        Human human=new Human("Vaibhav",23,"Male");
        System.out.println(human);
        System.out.println("hashCode Manual: " +human.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(human));
        System.out.println("================================================================");
        Car car=new Car("2018",26,"Black");
        System.out.println(car);
        System.out.println("hashCode Manual: " +car.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(car));
        System.out.println("================================================================");
        Bike bike=new Bike("BMW",6,"Spots");
        System.out.println(bike);
        System.out.println("hashCode Manual: " +bike.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(bike));
        System.out.println("================================================================");
        Dog dog=new Dog("German Shepheard",10,"Huge");
        System.out.println(dog);
        System.out.println("hashCode Manual: " +dog.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(dog));
        System.out.println("================================================================");
        Cat cat=new Cat("Persian",10,"White");
        System.out.println(cat);
        System.out.println("hashCode Manual: " +cat.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(cat));
        System.out.println("================================================================");
        Truck truck=new Truck("2015",100,"V8-Engine");
        System.out.println(truck);
        System.out.println("hashCode Manual: " +truck.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(truck));
        System.out.println("================================================================");
        Plane plane=new Plane("Indigo",100,"V8-Engine");
        System.out.println(plane);
        System.out.println("hashCode Manual: " +plane.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(plane));
        System.out.println("================================================================");
        Soap soap=new Soap("Rin",100,"Jasmine");
        System.out.println(soap);
        System.out.println("hashCode Manual: " +soap.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(soap));
        System.out.println("================================================================");
        Cloth cloth=new Cloth("Jeans","Red","XL");
        System.out.println(cloth);
        System.out.println("hashCode Manual: " +cloth.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(cloth));
        System.out.println("================================================================");
        Refrigerator refrigerator=new Refrigerator("Hier",50,"Maroon");
        System.out.println(refrigerator);
        System.out.println("hashCode Manual: " +refrigerator.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(refrigerator));
        System.out.println("================================================================");
        Television television=new Television("MI",50,"400");
        System.out.println(television);
        System.out.println("hashCode Manual: " +television.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(television));
        System.out.println("================================================================");
        Book book=new Book("Diary","Vaibhav",500);
        System.out.println(book);
        System.out.println("hashCode Manual: " +book.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(book));
        System.out.println("================================================================");
        Pen pen=new Pen("Monitor","Black",5);
        System.out.println(pen);
        System.out.println("hashCode Manual: " +pen.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(pen));
        System.out.println("================================================================");
        Bed bed=new Bed("Wood",35,"Brown");
        System.out.println(bed);
        System.out.println("hashCode Manual: " +bed.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(bed));
        System.out.println("================================================================");
        Helmet helmet=new Helmet("ISI","Carbon Fiber",32);
        System.out.println(helmet);
        System.out.println("hashCode Manual: " +helmet.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(helmet));
        System.out.println("================================================================");
        Mug mug=new Mug("Plastic","Cyan",1);
        System.out.println(mug);
        System.out.println("hashCode Manual: " +mug.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(mug));
        System.out.println("================================================================");
        LaptopBag laptopBag=new LaptopBag("Polython",30,"Black");
        System.out.println(laptopBag);
        System.out.println("hashCode Manual: " +laptopBag.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(laptopBag));
        System.out.println("================================================================");
        Pillow pillow=new Pillow("Nylon","Normal","White");
        System.out.println(pillow);
        System.out.println("hashCode Manual: " +pillow.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(pillow));
        System.out.println("================================================================");
        Computer computer=new Computer("Asus",16,"RTX");
        System.out.println(computer);
        System.out.println("hashCode Manual: " +computer.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(computer));
        System.out.println("================================================================");
        Guitar guitar=new Guitar("Rock",10,"Electric");
        System.out.println(guitar);
        System.out.println("hashCode Manual: " +guitar.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(guitar));
        System.out.println("================================================================");
        Camera camera=new Camera("Nikon",248,"Focus");
        System.out.println(camera);
        System.out.println("hashCode Manual: " +camera.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(camera));
        System.out.println("================================================================");
        Microwave microwave=new Microwave("Samsung",10,"Black");
        System.out.println(microwave);
        System.out.println("hashCode Manual: " +microwave.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(microwave));
        System.out.println("================================================================");
        Suitcase suitcase=new Suitcase("Skybag",50,"Blue");
        System.out.println(suitcase);
        System.out.println("hashCode Manual: " +suitcase.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(suitcase));
        System.out.println("================================================================");
        VaccumeCleaner vaccumeCleaner=new VaccumeCleaner("Lenvo",10,"Silver");
        System.out.println(vaccumeCleaner);
        System.out.println("hashCode Manual: " +vaccumeCleaner.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(vaccumeCleaner));
        System.out.println("================================================================");
        Treadmill treadmill=new Treadmill("Acer",10,"Silver");
        System.out.println(treadmill);
        System.out.println("hashCode Manual: " +treadmill.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(treadmill));
        System.out.println("================================================================");
        AirConditioner airConditioner=new AirConditioner("Dell",50,"White","500Rs");
        System.out.println(airConditioner);
        System.out.println("hashCode Manual: " +airConditioner.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(airConditioner));
        System.out.println("================================================================");
        Toaster toaster=new Toaster("Dell",40,"White");
        System.out.println(toaster);
        System.out.println("hashCode Manual: " +toaster.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(toaster));
        System.out.println("================================================================");
        Blender blender=new Blender("Lenovo",5000,"White");
        System.out.println(blender);
        System.out.println("hashCode Manual: " +blender.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(blender));
        System.out.println("================================================================");
        HairDryer hairDryer=new HairDryer("HP",500,"Black");
        System.out.println(hairDryer);
        System.out.println("hashCode Manual: " +hairDryer.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(hairDryer));
        System.out.println("================================================================");
        Bicycle bicycle=new Bicycle("FireFox",50,"Black");
        System.out.println(bicycle);
        System.out.println("hashCode Manual: " +bicycle.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(bicycle));
        System.out.println("================================================================");
        MicrowaveOven microwaveOven=new MicrowaveOven("HP",500,"Blue");
        System.out.println(microwaveOven);
        System.out.println("hashCode Manual: " +microwaveOven.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(microwaveOven));
        System.out.println("================================================================");
        Trolley trolley=new Trolley("Sky Bag","Leather","Black");
        System.out.println(trolley);
        System.out.println("hashCode Manual: " +trolley.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(trolley));
        System.out.println("================================================================");
        Printer printer=new Printer("Dell","Printing",900);
        System.out.println(printer);
        System.out.println("hashCode Manual: " +printer.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(printer));
        System.out.println("================================================================");
        Speaker speaker=new Speaker("JBL",600,"Orange");
        System.out.println(speaker);
        System.out.println("hashCode Manual: " +speaker.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(speaker));
        System.out.println("================================================================");
        WashingMachine washingMachine=new WashingMachine("IFB",50,"Cloths");
        System.out.println(washingMachine);
        System.out.println("hashCode Manual: " +washingMachine.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(washingMachine));
        System.out.println("================================================================");
        Lamp lamp=new Lamp("Hp","Brown",900);
        System.out.println(lamp);
        System.out.println("hashCode Manual: " +lamp.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(lamp));
        System.out.println("================================================================");
        SkateBoard skateBoard=new SkateBoard("JOYO","Carbon Fiber",90);
        System.out.println(skateBoard);
        System.out.println("hashCode Manual: " +skateBoard.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(skateBoard));
        System.out.println("================================================================");
        Tent tent=new Tent("Doco",11,"Green");
        System.out.println(tent);
        System.out.println("hashCode Manual: " +tent.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(tent));
        System.out.println("================================================================");
        Mattress mattress=new Mattress("Tocka",16,"Yellow");
        System.out.println(mattress);
        System.out.println("hashCode Manual: " +mattress.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(mattress));
        System.out.println("================================================================");
        StandMixer standMixer=new StandMixer("Bajaz",1100,"Yellow");
        System.out.println(standMixer);
        System.out.println("hashCode Manual: " +standMixer.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(standMixer));
        System.out.println("================================================================");
        Lion lion=new Lion("America",11,"Huge");
        System.out.println(lion);
        System.out.println("hashCode Manual: " +lion.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(lion));
        System.out.println("================================================================");
        Tiger tiger=new Tiger("India",400,"Black-Yellow");
        System.out.println(tiger);
        System.out.println("hashCode Manual: " +tiger.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(tiger));
        System.out.println("================================================================");
        Eagle eagle=new Eagle("Mountain",70,"Rat");
        System.out.println(eagle);
        System.out.println("hashCode Manual: " +eagle.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(eagle));
        System.out.println("================================================================");
        Parrot parrot=new Parrot("Green","AnyWhere",true);
        System.out.println(parrot);
        System.out.println("hashCode Manual: " +parrot.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(parrot));
        System.out.println("================================================================");
        Penguin penguin=new Penguin("Antarctica",30,"Fish");
        System.out.println(penguin);
        System.out.println("hashCode Manual: " +penguin.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(penguin));
        System.out.println("================================================================");
        Kangaroo kangaroo=new Kangaroo("America",90,80);
        System.out.println(kangaroo);
        System.out.println("hashCode Manual: " +kangaroo.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(kangaroo));
        System.out.println("================================================================");
        Horse horse=new Horse("Horse","brown",8);
        System.out.println(horse);
        System.out.println("hashCode Manual: " +horse.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(horse));
        System.out.println("================================================================");
        Zebra zebra=new Zebra("Amazon","black and white","Grass");
        System.out.println(zebra);
        System.out.println("hashCode Manual: " +zebra.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(zebra));
        System.out.println("================================================================");
        Duck duck=new Duck("White"," Water",true);
        System.out.println(duck);
        System.out.println("hashCode Manual: " +duck.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(duck));
        System.out.println("================================================================");
        Bear bear=new Bear("Forest",150,"Fish");
        System.out.println(bear);
        System.out.println("hashCode Manual: " +bear.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(bear));
        System.out.println("================================================================");
        Whale whale=new Whale("water",8000,"Fish");
        System.out.println(whale);
        System.out.println("hashCode Manual: " +whale.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(whale));
        System.out.println("================================================================");
        Dolphine dolphine=new Dolphine("Water",400,false);
        System.out.println(dolphine);
        System.out.println("hashCode Manual: " +dolphine.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(dolphine));
        System.out.println("================================================================");
        Wolf wolf=new Wolf("Land",40,"Rabbit");
        System.out.println(wolf);
        System.out.println("hashCode Manual: " +wolf.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(wolf));
        System.out.println("================================================================");
        Crocodile crocodile=new Crocodile("Water",20,"Anything Small Animal");
        System.out.println(crocodile);
        System.out.println("hashCode Manual: " +crocodile.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(crocodile));
        System.out.println("================================================================");
        Koala koala=new Koala("Land","fish",true);
        System.out.println(koala);
        System.out.println("hashCode Manual: " +koala.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(koala));
        System.out.println("================================================================");
        Swan swan=new Swan("White","Water",20);
        System.out.println(swan);
        System.out.println("hashCode Manual: " +swan.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(swan));
        System.out.println("================================================================");
        Panda panda=new Panda("Forest","Fish",false);
        System.out.println(panda);
        System.out.println("hashCode Manual: " +panda.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(panda));
        System.out.println("================================================================");
        Parakeet parakeet=new Parakeet("White","Forest",true);
        System.out.println(parakeet);
        System.out.println("hashCode Manual: " +parakeet.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(parakeet));
        System.out.println("================================================================");
        Tortoise tortoise=new Tortoise("Water",200,"Fish");
        System.out.println(tortoise);
        System.out.println("hashCode Manual: " +tortoise.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(tortoise));
        System.out.println("================================================================");
        Bat bat=new Bat("Forest",19,true);
        System.out.println(bat);
        System.out.println("hashCode Manual: " +bat.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(bat));
        System.out.println("================================================================");
        Ostrich ostrich=new Ostrich("America",150,false);
        System.out.println(ostrich);
        System.out.println("hashCode Manual: " +ostrich.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(ostrich));
        System.out.println("================================================================");
        Seagull seagull=new Seagull("India",15,"Fish");
        System.out.println(seagull);
        System.out.println("hashCode Manual: " +seagull.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(seagull));
        System.out.println("================================================================");
        SmartPhone smartPhone=new SmartPhone("MI",128,true);
        System.out.println(smartPhone);
        System.out.println("hashCode Manual: " +smartPhone.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(smartPhone));
        System.out.println("================================================================");
        SmartWatch smartWatch=new SmartWatch("Apple",true,true);
        System.out.println(smartWatch);
        System.out.println("hashCode Manual: " +smartWatch.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(smartWatch));
        System.out.println("================================================================");
        TeddyBear teddyBear=new TeddyBear("White",true,true);
        System.out.println(teddyBear);
        System.out.println("hashCode Manual: " +teddyBear.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(teddyBear));
        System.out.println("================================================================");
        Snake snake=new Snake("Snake",true,true);
        System.out.println(snake);
        System.out.println("hashCode Manual: " +snake.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(snake));
        System.out.println("================================================================");
        Rabbit rabbit=new Rabbit("rabbit",true,true);
        System.out.println(rabbit);
        System.out.println("hashCode Manual: " +rabbit.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(rabbit));
        System.out.println("================================================================");
        Shark shark=new Shark("Fish",true,true);
        System.out.println(shark);
        System.out.println("hashCode Manual: " +shark.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(shark));
        System.out.println("================================================================");
        Cow cow=new Cow("Nandi",true,true);
        System.out.println(cow);
        System.out.println("hashCode Manual: " +cow.hashCode());
        System.out.println("hashCode Original: " +System.identityHashCode(cow));






    }
}
