package com.xworkz.Runner;

import com.xworkz.Internal.*;
import com.xworkz.external.*;

public class InterfaceRunner {
    public static void main(String[] args) {

        System.out.println("=====================1====================");
        Customer customer = new Customer();
        customer.washHand();
        customer.keepClean();
        customer.payBefore();
        customer.wearMask();
        System.out.println("=====================2====================");
        People people = new People();
        people.book();
        people.time();
        people.keepClean();
        people.pay();
        System.out.println("=====================3====================");
        Room room = new Room();
        room.peopleInRoom();
        room.bedClean();
        room.keepClean();
        room.sleep();
        System.out.println("=====================4====================");
        Student student = new Student();
        student.time();
        student.uniform();
        student.completeHomework();
        student.extraCurricular();
        System.out.println("=====================5====================");
        ShopCustomer shopCustomer = new ShopCustomer();
        shopCustomer.openShop();
        shopCustomer.closeShop();
        shopCustomer.payBefore();
        shopCustomer.shopTiming();
        System.out.println("=====================6====================");
        TrafficRuleForPeople trafficRuleForPeople = new TrafficRuleForPeople();
        trafficRuleForPeople.noHorn();
        trafficRuleForPeople.speedLimit();
        trafficRuleForPeople.wearHelmet();
        trafficRuleForPeople.trafficLight();
        System.out.println("=====================7====================");
        BWM bwm = new BWM();
        bwm.noRacing();
        bwm.noStreetRacing();
        bwm.noIllegalModifications();
        bwm.carMaintenance();
        System.out.println("=====================8====================");
        Python python = new Python();
        python.noDisrespect();
        python.noDisruption();
        python.noInappropriateContent();
        python.programDuration();
        System.out.println("=====================9====================");
        WashRoom washRoom = new WashRoom();
        washRoom.noLittering();
        washRoom.noVandalism();
        washRoom.noExcessiveNoise();
        washRoom.washRoomCleanliness();
        System.out.println("=====================10====================");
        CarVehicle carVehicle = new CarVehicle();
        carVehicle.noSpeeding();
        carVehicle.noDrunkDriving();
        carVehicle.wearSeatBelt();
        carVehicle.carMaintenance();
        System.out.println("=====================11====================");
        Charger charger = new Charger();
        charger.noOvercharging();
        charger.noShortCircuit();
        charger.noFakeCharger();
        charger.chargerSafety();
        System.out.println("=====================12====================");
        CollageStudent collageStudent = new CollageStudent();
        collageStudent.noDrugs();
        collageStudent.noSmoking();
        collageStudent.noRagging();
        collageStudent.staySilent();
        System.out.println("=====================13====================");
        DriveBike driveBike = new DriveBike();
        driveBike.noDrinkAndDrive();
        driveBike.noOvertaking();
        driveBike.obeyTrafficSignals();
        driveBike.wearHelmet();
        System.out.println("=====================14====================");
        Laptop laptop = new Laptop();
        laptop.noOverheating();
        laptop.noDataLoss();
        laptop.noVirus();
        laptop.noFakeSoftware();
        System.out.println("=====================15====================");
        GovtForPeople govtForPeople = new GovtForPeople();
        govtForPeople.noCorruption();
        govtForPeople.noCrime();
        govtForPeople.noTerrorism();
        govtForPeople.noFakeNews();
        System.out.println("=====================16====================");
        Restaurant restaurant = new Restaurant();
        restaurant.noDamageToProperty();
        restaurant.noUnauthorizedAccess();
        restaurant.noUnrulyBehavior();
        restaurant.noFakeFood();
        System.out.println("=====================17====================");
        Website website = new Website();
        website.noMalware();
        website.noPhishing();
        website.noPopups();
        website.noFakeWebsites();
        System.out.println("=====================18====================");
        Chair chair = new Chair();
        chair.noDamageToProperty();
        chair.noUnauthorizedAccess();
        chair.noUnrulyBehavior();
        chair.fourLegs();
        System.out.println("=====================19====================");
        Bus bus = new Bus();
        bus.noEating();
        bus.noLittering();
        bus.noDisruption();
        bus.noFakeTickets();
        System.out.println("=====================20====================");
        Food food = new Food();
        food.noEating();
        food.eatComplete();
        food.noWasting();
        food.noFakeFood();
        System.out.println("=====================21====================");
        Home home = new Home();
        home.timeToSleep();
        home.timeToWakeUp();
        home.cleanHouse();
        home.doNotDisturb();
        System.out.println("=====================22====================");
        Alarm alarm = new Alarm();
        alarm.setAlarm();
        alarm.snoozeAlarm();
        alarm.resetAlarm();
        alarm.noFakeAlarm();
        System.out.println("=====================23====================");
        Trainer trainer = new Trainer();
        trainer.timeToTrain();
        trainer.timeToEat();
        trainer.timeToSleep();
        trainer.noFakeTrainer();
        System.out.println("=====================24====================");
        Teacher teacher = new Teacher();
        teacher.timeToTeach();
        teacher.timeToEat();
        teacher.timeToSleep();
        teacher.noFakeTeacher();
        System.out.println("=====================25====================");
        Phone phone = new Phone();
        phone.timeToCall();
        phone.timeToText();
        phone.timeToVideoCall();
        phone.noFakePhone();
        System.out.println("=====================26====================");
        Volume volume = new Volume();
        volume.timeToSpeak();
        volume.volume();
        volume.timeToListen();
        volume.noFakeSpeaker();
        System.out.println("=====================27====================");
        Hostel hostel = new Hostel();
        hostel.timeToDoLaundry();
        hostel.timeToGoOut();
        hostel.timeToReturn();
        hostel.dinnerTime();
        System.out.println("=====================28====================");
        Thar thar = new Thar();
        thar.timeToRefuel();
        thar.timeToWash();
        thar.timeToService();
        thar.noFakeCar();
        System.out.println("=====================29====================");
        NetWorkRule network = new Network();
        network.timeToConnect();
        network.timeToDisconnect();
        network.timeToTransferData();
        network.noFakeNetwork();
        System.out.println("=====================30====================");
        SoapRule soap = new Soap();
        soap.timeToUseSoap();
        soap.timeToWashHands();
        soap.timeToTakeBath();
        soap.noFakeSoap();
        System.out.println("=====================31====================");
        Company company = new Company();
        company.timeToWork();
        company.timeToTakeBreak();
        company.timeToLeaveOffice();
        customer.keepClean();
        System.out.println("=====================32====================");
        TV tv = new TV();
        tv.timeToWatchTV();
        tv.timeToChangeChannel();
        tv.timeToSwitchOffTV();
        tv.noFakeTV();
        System.out.println("=====================33====================");
        HairDryer hairDryer = new HairDryer();
        hairDryer.timeToSwitchOn();
        hairDryer.timeToDryHair();
        hairDryer.timeToSwitchOff();
        hairDryer.noFakeHairDryer();
        System.out.println("=====================34====================");
        Bank bank = new Bank();
        bank.timeToOpenBank();
        bank.timeToDepositMoney();
        bank.timeToCloseBank();
        bank.noFakeBank();
        System.out.println("=====================35====================");
        ShowRoom showRoom = new ShowRoom();
        showRoom.timeToOpenShowRoom();
        showRoom.timeToDisplayItems();
        showRoom.timeToCloseShowRoom();
        showRoom.noFakeShowRoom();
        System.out.println("=====================36====================");
        Door door = new Door();
        door.timeToOpenDoor();
        door.timeToLockDoor();
        door.timeToCloseDoor();
        door.noFakeDoor();
        System.out.println("=====================37====================");
        BarberRule barberRule = new Barber();
        barberRule.timeToOpenBarberShop();
        barberRule.timeToCutHair();
        barberRule.timeToCloseBarberShop();
        barberRule.noFakeBarberShop();
        System.out.println("=====================38====================");
        ParlimentRule parlimentRule = new Parliment();
        parlimentRule.timeToOpenParliment();
        parlimentRule.timeToDiscussBills();
        parlimentRule.timeToCloseParliment();
        parlimentRule.noFakeParliment();
        System.out.println("=====================39====================");
        LibraryRule libraryRule = new Library();
        libraryRule.timeToOpenLibrary();
        libraryRule.timeToReadBooks();
        libraryRule.timeToCloseLibrary();
        libraryRule.noFakeLibrary();
        System.out.println("=====================40====================");
        CleaningRule cleaningRule = new Cleaning();
        cleaningRule.timeToCleanHouse();
        cleaningRule.timeToCleanCar();
        cleaningRule.timeToCleanBathroom();
        cleaningRule.noFakeCleaning();
        System.out.println("=====================41====================");
        Camera camera = new Focus();
        camera.timeToCapturePhoto();
        camera.timeToRecordVideo();
        camera.timeToZoomIn();
        camera.noFakeCamera();
        System.out.println("=====================42====================");
        ElectricityRule electricityRule = new Electric();
        electricityRule.timeToOpenElectricity();
        electricityRule.timeToUseElectricity();
        electricityRule.timeToCloseElectricity();
        electricityRule.noFakeElectricity();
        System.out.println("=====================43====================");
        CodingRule coadingRule = new Code();
        coadingRule.timeToCode();
        coadingRule.timeToDebug();
        coadingRule.timeToTest();
        coadingRule.noFakeCoding();
        coadingRule.noFakeCoding();
        System.out.println("=====================44====================");
        ComputerRule computerRule = new Computer();
        computerRule.timeToCompile();
        computerRule.timeToRun();
        computerRule.timeToExecute();
        computerRule.noFakeComputer();
        System.out.println("=====================45====================");
        EmployeeRule employeeRule = new Emloyee();
        employeeRule.timeToAttendMeeting();
        employeeRule.timeToCompleteTask();
        employeeRule.timeToSubmitReport();
        employeeRule.noFakeEmployee();
        System.out.println("=====================46====================");
        HospitalRule hospitalRule = new Hospital();
        hospitalRule.timeToAdmitPatient();
        hospitalRule.timeToDischargePatient();
        hospitalRule.timeToConsultDoctor();
        hospitalRule.noFakeHospital();
        System.out.println("=====================47====================");
        FireRule fireRule = new Fire();
        fireRule.timeToExtinguishFire();
        fireRule.timeToCallEmergencyServices();
        fireRule.timeToEvacuate();
        fireRule.noFakeFire();
        System.out.println("=====================48====================");
        WaterRule waterRule = new Water();
        waterRule.timeToBoilWater();
        waterRule.timeToPurifyWater();
        waterRule.timeToFillTank();
        waterRule.noFakeWater();
        System.out.println("=====================49====================");
        BagRule bagRule = new Bag();
        bagRule.timeToCarryBag();
        bagRule.timeToUnpackBag();
        bagRule.timeToPackBag();
        bagRule.noFakeBag();
        System.out.println("=====================50====================");
        JavaRule javaRule = new Java();
        javaRule.timeToCompileJava();
        javaRule.timeToRunJava();
        javaRule.timeToDebugJava();
        javaRule.noFakeJava();
        System.out.println("=====================51====================");
        RocketRule rocketRule = new Rocket();
        rocketRule.timeToLaunchRocket();
        rocketRule.timeToLandRocket();
        rocketRule.timeToRefuelRocket();
        rocketRule.noFakeRocket();
        System.out.println("=====================52====================");
        SecurityRule securityRule = new Security();
        securityRule.timeToCheckSecurity();
        securityRule.timeToSecureArea();
        securityRule.timeToReportIncident();
        securityRule.noFakeSecurity();
        System.out.println("=====================53====================");
        BottelRule bottelRule = new Bottel();
        bottelRule.timeToCheckBottel();
        bottelRule.timeToCleanBottel();
        bottelRule.timeToEmptyBottel();
        bottelRule.noFakeBottel();
        System.out.println("=====================54====================");
        DrivingRule drivingRule = new Drive();
        drivingRule.timeToStartDriving();
        drivingRule.timeToStopDriving();
        drivingRule.timeToParkCar();
        drivingRule.driveSafe();
        System.out.println("=====================55====================");
        ATMRule atmRule = new ATM();
        atmRule.timeToChangePin();
        atmRule.timeToWithdrawMoney();
        atmRule.timeToCheckBalance();
        atmRule.timeToDepositMoney();
        System.out.println("=====================56====================");
        ExamRule examRule = new Exam();
        examRule.timeToStartExam();
        examRule.timeToStopExam();
        examRule.timeToCheckAnswerSheet();
        examRule.noFakeExam();
        System.out.println("=====================57====================");
        BicycleRule bicycleRule = new Bicycle();
        bicycleRule.timeToCheckBicycle();
        bicycleRule.timeToParkBicycle();
        bicycleRule.timeToStopBicycle();
        bicycleRule.noFakeBicycle();
        System.out.println("=====================58====================");
        BuildingRule buildingRule = new Building();
        buildingRule.timeToCheckBuilding();
        buildingRule.timeToStartBuilding();
        buildingRule.timeToStopBuilding();
        buildingRule.noFakeBuilding();
        System.out.println("=====================59====================");
        TableRule tableRule = new Table();
        tableRule.timeToCleanTable();
        tableRule.timeToClearTable();
        tableRule.timeToDecorateTable();
        tableRule.noFakeTable();
        System.out.println("=====================60====================");
        MallRule mallRule = new Mall();
        mallRule.timeToCheckMall();
        mallRule.timeToStartMall();
        mallRule.timeToStopMall();
        mallRule.noFakeMall();
        System.out.println("=====================61====================");
        MartRule martRule = new Mart();
        martRule.timeToCheckMart();
        martRule.timeToStartMart();
        martRule.timeToStopMart();
        martRule.noFakeMart();
        System.out.println("=====================62====================");
        ProtectionRule protectionRule = new Protection();
        protectionRule.timeToCheckProtection();
        protectionRule.timeToStopProtection();
        protectionRule.timeToCheckSecurity();
        protectionRule.noFakeProtection();
        System.out.println("=====================63====================");
        CoupleRule coupleRule = new Couple();
        coupleRule.ruleToStartCouple();
        coupleRule.toUnderstandCouple();
        coupleRule.toLoyaltyCouple();
        coupleRule.noFakeCouple();
        System.out.println("=====================64====================");
        GirlFriendRule girlFriendRule = new Girlfriend();
        girlFriendRule.toLoyaltyGirlFriend();
        girlFriendRule.toUnderstandGirlFriend();
        girlFriendRule.toRespectGirlFriend();
        girlFriendRule.noFakeGf();
        System.out.println("=====================65====================");
        WifeRule wifeRule = new Wife();
        wifeRule.toLoveWife();
        wifeRule.toRespectWife();
        wifeRule.toSupportWife();
        wifeRule.noFakeWife();
        System.out.println("=====================66====================");
        ChildrenRule childrenRule = new Children();
        childrenRule.toLoveChildren();
        childrenRule.toTeachChildren();
        childrenRule.toPlayWithChildren();
        childrenRule.noFakeChildren();
        System.out.println("=====================67====================");
        OfficeRule officeRule = new Office();
        officeRule.toBeHonest();
        officeRule.toBePunctual();
        officeRule.toWorkWithTeam();
        officeRule.noFakeOffice();
        System.out.println("=====================68====================");
        SatelliteRule  satelliteRule=new Satellite();
        satelliteRule.toTeachTeamSatellite();
        satelliteRule.tofocusOnWorkSatellite();
        satelliteRule.toWorkWithTeamSatellite();
        satelliteRule.noFakeSatellite();
        System.out.println("=====================69====================");
        BoxingRule boxingRule = new Boxing();
        boxingRule.useGloves();
        boxingRule.useGloves();
        boxingRule.useShoe();
        boxingRule.noFakeBoxing();
        System.out.println("=====================70====================");
        PeopleRule peopleRule = new Person();
        peopleRule.toBeFriendly();
        peopleRule.toBeKind();
        peopleRule.toBeTrustworthy();
        peopleRule.noFakePeople();










    }
}
